apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    name: mynfs # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.1.1.5
    path: "/var/nfs/general"
