apiVersion: v1
kind: Service
metadata:
  name: test-ce
  namespace: ves-system
  labels:
    app: ver
spec:
  ports:
    - name: "ver-http"
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
      app: ver
