apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-transfer
  labels:
    app: money-transfer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-transfer
      version: v1
  template:
    metadata:
      labels:
        app: money-transfer
        version: v1
    spec:
      containers:
        - image: fauziramadhan/arcadia-money-transfer:latest
          imagePullPolicy: Always
          name: money-transfer
          env:
            - name: service_name
              value: money-transfer
          name: money-transfer
          ports:
            - containerPort: 9080
              protocol: TCP
        - name: nginx-sc
          image: fauziramadhan/nplusnap-unpriv:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: api-secret
              mountPath: /etc/nginx/api_secret.jwk
              subPath: api_secret.jwk
        - name: apigw-money-transfer
          image: reg.edgecnf.com/apps/arcadia-apigw:v2.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4010
          volumeMounts:
            - name: api-gw
              mountPath: /usr/src/prism/api-gw.json
              subPath: api-gw.json
        - name: apigw-loadgen
          image: reg.edgecnf.com/apps/newman:2.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: east-west-mt-to-be-postman
              mountPath: /tmp/east-west-mt-to-be-postman.json
              subPath: east-west-mt-to-be-postman.json
            - name: run-apigen-mt
              mountPath: /tmp/run-apigw-loadgen.sh
              subPath: run-apigw-loadgen.sh
      volumes:
        - name: default-conf
          configMap:
            name: sc-nginx-default-conf-9090-mt-cm
        - name: api-gw
          configMap:
            name: api-gw-mt.json
        - name: east-west-mt-to-be-postman
          configMap:
            name: east-west-mt-to-be-postman.json
        - name: run-apigen-mt
          configMap:
            name: run-apigen-mt.sh
            defaultMode: 0777
        - name: api-secret
          configMap:
            name: api-secret
