apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - name: frontend-80
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: frontend
